name: Cloudflare Gateway - Block Ads

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run blocklist update script
        env:
          CLO_API_TOKEN: ${{ secrets.API_TOKEN }}
          CLO_ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
        run: |
          # 1. Download the list
          curl -sSL https://raw.githubusercontent.com/btchimquackuk/cloudflare-gateway-block-ads/main/oisd_small_domains.txt -o oisd_small_domains.txt

          # 2. Install dependencies and run the sync script
          pip install requests
          python .github/workflows/sync_blocklist.py
